[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "cd backend-flask && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend-flask && python -u start.py"
