[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc"]

[phases.install]
cmds = [
  "cd backend-flask && pip install -r requirements.txt"
]

[start]
cmd = "cd backend-flask && python -u start.py"
